[general]
live_config_reload = true

[terminal.shell]
program = "wsl.exe"
args = ["-d", "ArchLinux", "--cd", "~"]

[window]
opacity = 0.8
decorations = "Full"

[font]
size = 10.5
normal = { family = "UDEV Gothic 35NF", style = "Regular" }

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
  { key = "C", mods = "Control", action = "Copy" },
  { key = "V", mods = "Control", action = "Paste" },

  { key = "Enter", mods = "Alt", action = "ToggleFullscreen" },
]
